import express from "express";
import FinanceController from "./controllers/finance.controller";
export const financeRoutes = express.Router();

financeRoutes.post("/finance/bank", FinanceController.createOrUpdateBank);
financeRoutes.get("/finance/banks", FinanceController.getBanks);
financeRoutes.post("/finance/financial-account", FinanceController.createFinancialAccount);
financeRoutes.get("/finance/financial-accounts", FinanceController.getFinancialAccounts);
financeRoutes.get("/finance/get-all-financial-account", FinanceController.getAllFinancialAccounts);
financeRoutes.post("/finance/deposit-money", FinanceController.depositMoney);
financeRoutes.post("/finance/add-expense", FinanceController.addExpense);
financeRoutes.post("/finance/transfer-money", FinanceController.transferMoney);
financeRoutes.get("/finance/financial-passbook", FinanceController.getFinancialPassbook);
financeRoutes.get("/finance/investments", FinanceController.getFinancialInvestments);
financeRoutes.get("/finance/all-investments", FinanceController.getAllFinancialInvestments);
financeRoutes.post("/finance/investment", FinanceController.createInvestment);
financeRoutes.post("/finance/invest-money", FinanceController.investMoney);
financeRoutes.get("/finance/overview", FinanceController.getFinancialOverview);
financeRoutes.get("/finance/financial-profile", FinanceController.getFinancialProfile);
financeRoutes.post("/finance/financial-profile", FinanceController.createFinancialProfile);
financeRoutes.get("/finance/expense-budget", FinanceController.getExpenseBudget);
financeRoutes.post("/finance/expense-budget", FinanceController.createOrUpdateExpenseBudget);
financeRoutes.get("/finance/yearly-expense", FinanceController.getYearlyExpenseByCategory);
financeRoutes.post("/finance/revert-transaction", FinanceController.revertTransaction);
financeRoutes.post("/finance/withdraw-investment-money", FinanceController.withdrawInvestmentMoney);